name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            cmake \
            git \
            pkg-config \
            libsodium-dev \
            libfreetype6-dev \
            libgl1-mesa-dev

      - name: Build and Install SDL3
        run: |
          git clone https://github.com/libsdl-org/SDL.git --depth 1
          cmake -S SDL -B SDL/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
          cmake --build SDL/build --config Release -j$(nproc)
          sudo cmake --install SDL/build

      - name: Build and Install SDL3_ttf
        run: |
          git clone https://github.com/libsdl-org/SDL_ttf.git --depth 1
          cmake -S SDL_ttf -B SDL_ttf/build -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=/usr/local
          cmake --build SDL_ttf/build --config Release -j$(nproc)
          sudo cmake --install SDL_ttf/build

      - name: Update Shared Library Cache
        run: sudo ldconfig

      - name: Build Project and Run Tests
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release
          ctest --test-dir build --output-on-failure
